#!/usr/bin/env bash

# extract javascript files from gau and parse them through SercetFinder
# ./jcollect domains.txt

while read SUB; do
	gau -subs $SUB | grep "\.js$" | anti-burl | grep -Eo "(http|https)://[a-zA-Z0-9./?=_-]*" | sort -u | tee -a javascript_files
done < $1


while read LINE; do 
	python3 /home/victor/Desktop/bugHunting/tools/secretfinder/SecretFinder.py -i $LINE -o cli | tee -a js_results
done < javascript_files